language: node_js
os:
  - linux
  - osx
node_js:
  - '12'
dist: trusty
sudo: false
install:
  - eval "$(curl -sL https://raw.githubusercontent.com/travis-ci/gimme/master/gimme | GIMME_GO_VERSION=master bash)"
script:
  - echo $(go version) && echo $GOPATH
  - npm run lint
notifications:
  email: false